### ISSUE TITLE
屏幕如何占满的?

### ISSUE THREAD

**Issue by SniperM99** [graviton1221/Danim#1]
请教一下, 看你的gif图,屏幕是被全部占满了, 这个是如何实现的?

**Comment by graviton1221** [comment]
让坐标轴原点在屏幕左下角，就可以了，具体可以看BubbleChart/bubble_constants.py里面的axes settings，其中RIGHT_MOST_X_ON_SCREEN 、TOP_MOST_Y_ON_SCREEN和NEWORIGIN这三个变量决定了坐标轴的位置

**Comment by SniperM99** [comment]
3QU
